[project]
name = "thabet_anam_v4"
authors = [
  { name = "Thabet Anam Customs Clearance", email = "Thabet.anam@gmail.com" }
]
description = "Customs clearance layer for ERPNext used by Thabet Anam"
requires-python = ">=3.14"
readme = "README.md"
license = { text = "MIT" }
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
erpnext = ">=16.0.0,<17.0.0"

[project.urls]
Repository = "https://github.com/737337328th/Thabet--Anam---erp"
